site_name: Lenovo CDRT Docs Site
site_url: https://docs.lenovocdrt.com/

theme:
  name: material
  logo: img/CDRT-REV-Red_s.png
  favicon: img/fav/favicon.ico
  font:
    text: Noto Sans
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: blue grey

plugins:
  - search
  - open-in-new-tab
  - redirects:
      redirect_maps:
        'guides/tbct/tbct_top.md': 'guides/tbct_v2/index.md'
        'guides/tbct_v2/tbct_v2_top.md': 'guides/tbct_v2/index.md'
        'guides/cv/index.md' : 'guides/lcv/index.md'
  - awesome-nav

markdown_extensions:
  - admonition
  - tables
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: ......span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - toc:
      permalink: "#"

extra:
  analytics:
    provider: google
    property: G-Q3G8XPJ5GY
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences such as light and dark mode, as well as to measure anonymous usage data to determine effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
    actions:
      - accept
      - reject

copyright: |
  &copy; 2026 <a href="https://docs.lenovocdrt.com"  target="_blank" rel="noopener">Lenovo Commercial Deployment Readiness Team</a><br><a href="#__consent" style="text-decoration:underline;">Change cookie settings</a>

extra_css :
  - stylesheets/extra.css
